apiVersion: v1
kind: Service
metadata:
     name: nginx-service
     labels:
         app: nginx
         role: dev
spec:
   selector:
        app: nginx
        role: dev
   type: NodePort
   ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
   externalIPs:
   - 192.168.99.20
   - 192.168.99.21

