apiVersion: v1
kind: Service
metadata:
     name: myservice
     labels:
         app: jenkins
spec:
   selector:
        app: jenkins
   type: NodePort
   ports:
   - protocol: TCP
     port: 8081
     targetPort: 8080
     nodePort: 30001

