apiVersion: v1
kind: Service
metadata:
     name: nfs-sfs-headlessservice
     labels:
         app: nginx
spec:
   selector:
        app: nginx
   ports:
   - protocol: TCP
     port: 80
     name: web
   clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
     name: nfs-sfs
spec:
   serviceName: nfs-sfs-headlessservice
   replicas: 4
   selector:
        matchLabels:
               app: nginx
   template:
      metadata:
        name: mypod
        labels:
          app: nginx
      spec:
       containers:
       - name: mycont
         image: nginx
         imagePullPolicy: IfNotPresent
         volumeMounts:
         - name: my-pvc
           mountPath: /demo
   volumeClaimTemplates:
   - metadata:
          name: my-pvc
     spec:
        storageClassName: pv-demo
        resources:
          requests:
             storage: "200Mi"
        accessModes:
        - ReadWriteOnce


