apiVersion: apps/v1
kind: Deployment
metadata:
     name: nginx-deploy
     labels:
        app: nginx-dp
spec:
  replicas: 2
  selector:
       matchLabels:
             app: nginx-dp
  template:
      metadata:
          name: nginx-pod
          labels:
             app: nginx-dp
      spec:
       containers:
       - name: mynginx-cont
         image: nginx
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 80
