apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
        app: nginx-dp
spec:
   selector:
        app: nginx-dp
   type: NodePort
   ports:
   - protocol: TCP
     port: 8083
     targetPort: 80
     nodePort: 30002
