apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: db-storage
     annotations:
             volume.beta.kubernetes.io/storage-class: "standard"
spec:
   resources:
         requests:
             storage: "200Mi"
   accessModes:
   - ReadWriteOnce
