apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
        app: nginx
spec:
   containers:
   - name: myonct
     image: nginx
     imagePullPolicy: IfNotPresent
     resources:
        requests:
           ephemeral-storage: "500Mi"
        limits:
           ephemeral-storage: "600Mi"

