apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
        app: nginx
spec:
  containers:
  - name: mycont
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: username
      value: "ramesh123"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-vol
      mountPath: /usr/share/nginx/index.html
  - name: mycont1
    image: debian
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: my-vol
      mountPath: /pod-data
    command: ["/bin/bash"]
    args: ["-c","echo hello this s for testing > /pod-data/index.html && sleep 3000"]
  volumes:
  - name: my-vol
    emptyDir: {}     
