apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       app: nginx
spec:
  containers:
  - name: mycont
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: mymvol
      mountPath: "/demo"
  volumes:
  - name: mymvol
    persistentVolumeClaim:
            claimName: my-pvc
