apiVersion: v1
kind: Pod
metadata:
     name: mypod
     labels:
         app: nginx
         env: dev
spec:
  nodeSelector:
          env: prod
  containers:
  - name: mycont
    image: nginx
    ports:
    - containerPort: 80
    resources:
       requests:
          cpu: "250m"
          memory: "350M"
       limits:
          cpu: "350m"
          memory: "400M"
    env:
    - name: myname
      value: "ramesh" 
  hostNetwork: true 
