apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: my-pvc
     labels:
         type: local
spec:
   storageClassName: pv-demo
   resources:
        requests:
            storage: "400Mi"
   accessModes:
   - ReadWriteMany
