apiVersion: v1
kind: ReplicationController
metadata:
   name: my-rc
   labels:
       app: nginx
spec:
   replicas: 3
   selector:
         app: nginx
   template:
      metadata:
          name: mypod-1
          labels:
              app: nginx
      spec:
        containers:
        - name: mycont-1
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
