apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: my-rs
spec:
 replicas: 5
 selector:
     matchLabels:
           app: nginx
 template:
     metadata:
         name: my-pod-rs
         labels:
            app: nginx
     spec:
       containers:
       - name: mycont-rs
         image: nginx
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 80
