apiVersion: v1
kind: Pod
metadata:
    name: mypod-env
    labels:
       app: nginx-app
spec:
  containers:
  - name: mycnt
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: user_name
      valueFrom:
          secretKeyRef:
                name: my-secret
                key: userfile
