apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       app: nginx
spec:
  containers:
  - name: mycont
    image: nginx
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","echo one container is running ; sleep 60"]
    volumeMounts:
    - name: myvol-dir
      mountPath: /opt
  - name: mycont1
    image: nginx
    imagePullPolicy: IfNotPresent
    #command: ["sh","-c","touch file{1..5}"]
    volumeMounts:
    - name: myvol-dir
      mountPath: /demo
      
  volumes:
  - name: myvol-dir
    emptyDir: {}

