apiVersion: v1
kind: ServiceAccount
metadata:
     name: nfs-client-provisionar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
     name: nfs-client-provisionar-runner
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get","watch","create","delete","list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","watch","update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
     name: run-nfs-client-provisionar
subjects:
- name: nfs-client-provisionar
  kind: ServiceAccount
  namespace: default
roleRef:
    name: nfs-client-provisionar-runner
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: role-nfs-client-provisionar
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
      name: roleb-nfs-clinet-provisionar
subjects:
- kind: ServiceAccount
  name: nfs-client-provisionar
  namespace: default
roleRef:
    kind: Role
    name: role-nfs-client-provisionar
    apiGroup: rbac.authorization.k8s.io

